name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      # Checkout source
      - uses: actions/checkout@v4

      # Set up Python (no Poetry cache because poetry.lock is not committed)
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install Poetry
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      # Install project + dev dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      # Run tests with coverage (dummy tokens avoid real API calls)
      - name: Run tests & enforce 80 % coverage
        env:
          GROQ_API_KEY: dummy
          GITHUB_TOKEN: dummy
        run: |
          poetry run coverage run \
            --omit='*/tests/*,*/.venv/*,*/b3th/cli.py,*/b3th/gh_api.py' \
            -m pytest -qq
          poetry run coverage report --fail-under=80
