name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Python & Poetry cache
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      # Install deps
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      # Tests + coverage
      - name: Run tests & enforce coverage
        env:
          # Dummy tokens so code paths that read env vars never fail
          GROQ_API_KEY: "dummy"
          GITHUB_TOKEN: "dummy"
        run: |
          poetry run coverage run \
            --omit='*/tests/*,*/.venv/*' \
            -m pytest -qq
          poetry run coverage report --fail-under=80
