name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run tests (pytest-cov)
        env:
          # Prevent real secrets from affecting tests that simulate "missing" config
          GITHUB_TOKEN: ""
          GITHUB_PAT: ""
          GROQ_API_KEY: ""
        run: |
          poetry run pytest -q
